server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pos?serverTimezone=Asia/Seoul
    username: pos
    password: pos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
      security:    oauth2:      client:        registration:
         google:
            client-id: 516008453741-iejt6m4b18keil0o0tajv1it7bv333kq.apps.googleusercontent.com
            client-secret: I8sb_kyXW942jpxOhVXMNqds
            scope:            - email
            - profile
            
         facebook:
            client-id: 383244536098752
            client-secret: 011d380b0fc5914c1c0d6eb5e42031c9
            scope:
            - email
            - public_profile
          
         naver:
           client-id: kl5Ou8KkIxguhNueNQTf
           client-secret: HJb0Mb5P4a
           scope:            - id
            - email
            - name
           authorization-grant-type: authorization_code
           redirect-uri: http://localhost:8080/login/oauth2/code/naver
           client-name: Naver
   
         kakao:
          client-id: 911dc0d1e36ed65789c4b11f7e2ed09f
          client-secret: aWRgUc5LItfRHJ9SCGuvRX4VAvTU1WDU
          scope:
            - account_email
            - profile
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          client-name: Kakao
          client-authentication-method: POST
        
          provider:          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
         
          kakao:
            authorization-uri:  https://kauth.kakao.com/oauth/authorize
            token-uri:  https://kauth.kakao.com/oauth/token
            user-info-uri:  https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            
          
           
           
      

       
          
            
              
           
            
                   
            
          
     
      
      